//
//  MTSyncContainerConstants.h
//  MTMeasure&Go
//
//  Created by Andrejs Cernikovs on 5/23/13.
//  Copyright (c) 2013 grandcentrix GmbH. All rights reserved.
//

//modeHeader1    - GLM 100
#define MEAS_MODE_GETSYNC 0
#define MEAS_MODE_SINGLE 1
#define MEAS_MODE_AREA 2
#define MEAS_MODE_VOLUME 3
#define MEAS_MODE_ANGLE 4
#define MEAS_MODE_RAIL 5
#define MEAS_MODE_MIN_MAX 6
#define MEAS_MODE_INDIRECT_HEIGHT 7
#define MEAS_MODE_INDIRECT_LENGTH 8
#define MEAS_MODE_DOUBLE_INDIRECT_HEIGHT 9
#define MEAS_MODE_WALL_AREA 10
#define MEAS_MODE_SETUP 11
#define MEAS_MODE_CALIBRATION 12
#define MEAS_MODE_MEAS_LIST 13
#define MEAS_MODE_TRAPEZOID 14
#define MODE_ERROR_RESPONSE 63


// Mode Headers - GLM 50c

#define MODE_NO_ACTION  0
#define MODE_SINGLE_DISTANCE  1
#define MODE_CONTINUOUS_DISTANCE  2
#define MODE_AREA_PART_1  3
#define MODE_AREA_FINAL  4
#define MODE_VOLUME_PART_1  5
#define MODE_VOLUME_PART_2  6
#define MODE_VOLUME_FINAL  7
#define MODE_SINGLE_ANGLE  8
#define MODE_CONTINUOUS_ANGLE  9
#define MODE_INDIRECT_HEIGHT  10
#define MODE_INDIRECT_LENGTH  11
#define MODE_DOUBLE_INDIRECT_HEIGHT_PART_1  12
#define MODE_DOUBLE_INDIRECT_HEIGHT_FINAL  13
#define MODE_WALL_AREA_PART_1  14
#define MODE_WALL_AREA_FINAL  15
#define MODE_CALCULATED_DISTANCE_PLUS  16
#define MODE_CALCULATED_DISTANCE_MINUS  17
#define MODE_CALCULATED_AREA_PLUS  18
#define MODE_CALCULATED_AREA_MINUS  19
#define MODE_CALCULATED_VOLUME_PLUS  20
#define MODE_CALCULATED_VOLUME_MINUS  21
#define MODE_SINGLE_LEVEL  22
#define MODE_CONTINUOUS_LEVEL  23
#define MODE_TRAPEZOID_PART_1  24
#define MODE_TRAPEZOID_PART_2  25
#define MODE_TRAPEZOID_PART_FINAL  26
// control modes
#define MODE_GET_LIST_ITEM_BY_INDEX  58
#define MODE_TEMPERATURE_AND_SOC  59
#define MODE_SET_DEV_MODE  60
#define MODE_SET_ANGLE_REFERENCE  61
#define MODE_SET_DISTANCE_REFERENCE  62


//Control modes

#define INDICATOR_FINAL_MESSAGE 0

// switchMode
#define MODE_SWITCH_ON 1
#define MODE_SWITCH_OFF 0


//signalOperation
#define OPERATION_START 1
#define OPERATION_STOP 0
#define OPERATION_UNDEFINED OPERATION_STOP

//syncControl
#define MODE_AUTOSYNC_CONTROL_ON 1
#define MODE_AUTOSYNC_CONTROL_OFF 0

// distReference constants
#define DIST_REFERENCE_FRONT 0
#define DIST_REFERENCE_TRIPOD 1
#define DIST_REFERENCE_REAR 2
#define DIST_REFERENCE_PIN 3

// angleReference constants
#define ANGLE_REFERENCE_BACK 0
#define ANGLE_REFERENCE_SIDE 1
#define ANGLE_REFERENCE_RAIL 2
#define ANGLE_REFERENCE_INVALID 7

//calcIndicator
#define CALCIND_IGNORE 0
#define CALCIND_PLUS 1
#define CALCIND_MINUS 2
#define CALCIND_PLUS_EQUAL 3
#define CALCIND_MINUS_EQUAL 4

// deviceConfig
#define CONFIG_UNITS_METRIC 0
#define CONFIG_UNITS_IMPERIAL 1

// warnings
#define WARNING_TEMPERATURE_STATUS_OFF 0
#define WARNING_TEMPERATURE_STATUS_ON 1

#define WARNING_BATTERY_STATUS_OFF 0
#define WARNING_BATTERY_STATUS_ON 1

// Device Mode
#define MODE_READ_ONLY 0

